### PR TITLE
Deployment issues

### PR DESCRIPTION
**Pull request by mrossi113**
**DO NOT MERGE**

Using this branch to test the `demo-run-app` issue. This way not to actual touch the `demo-run-app`. This way to test using the code from `demo-run-app` as well as in the CodePipeline to see if works.

**This will need to be merged into the `demo-run-app` branch first before the `demo-run-app` gets merged into develop.**

### CODE REVIEW

**Comment by mrossi113** [comment]
**Still working on this branch for JSP files are not loading correctly**

**Comment by mrossi113** [comment]
@cruoti this can be merged into `demo-run-app` the elastic beanstalk works with this branch. Except issue with the jsp files are not loaded correctly. I will look into further tomorrow spent a few hours on it already.

**Comment by cruoti** [comment]
@mrossi113 

Thanks for all the work.  I will get working on it after work and dinner tonight.  Sometime around 6:30-7:00.  I doubt I'll have it ready for our 7:30 meeting, but I'll put in more work tonight to try and figure it out as well.

**Comment by mrossi113** [comment]
@cruoti closing the PR as well if needed the branch will still be available.

**Pull request closed without merging**
