### PR TITLE
New code layout

### PR DESCRIPTION
**Pull request by mrossi113**
This new code layout to have much clean code from the previous work. The java classes and html pages were brought into this branch. The jsp files that were created are clean with no code from the previous PRs. For this period of time I added the links right on the index.html until we have fix all the code. This will be updated before turning in the assignment 

URL: http://custom-env.pac9mpkmm6.us-east-1.elasticbeanstalk.com

I have changed the CodePipeline to run when every a commit has occurred from this PR. If you need to view with elastic beanstalk I would commit to this branch. If you feel that better to build off of this branch and need to use the Elastic Beanstalk let me know. 

**DO NOT MERGE THIS BRANCH INTO DEVELOP YET**

### CODE REVIEW

**Comment by mrossi113** [comment]
@cruoti I've started to add html code into the jsp file and it's appearing with no problem. http://custom-env.pac9mpkmm6.us-east-1.elasticbeanstalk.com/WebContent/dashboard.jsp 

Next step work on the adding the java code to jsp files.

**Comment by cruoti** [comment]
@mrossi113 

Sorry for not having looked at this yet.  I'm starting to work on things now.

**Comment by cruoti** [comment]
@mrossi113 

Can you send me your project files for IntelliJ?  I've never been able to get a project to run when the index.html file is in the main directory and not in the web directory.  I'm sure my issue is something simple, maybe your project files can help get me in the right direction.  

Thanks.

**Comment by mrossi113** [comment]
@cruoti I've been using Eclipse now for debugging the issue I'm seeing with the java code and JSP files. The Eclipse is giving me warning and errors to figure out why the code is not working. If you need to just make a copy of the index.html file into the web directory and just make sure to never push it to the branch or you could just remove it if you need a clean branch.

**Comment by cruoti** [comment]
@mrossi113 

As soon as I add the tags for JSTL we get the 500 error again. ...

**Comment by mrossi113** [comment]
@cruoti we probably should close this branch. If you need anything I will leave the branch which means I won't delete it yet.

**Pull request closed without merging**
